[package]
name = "within/pemci"
version = "0.0.2"
description = "Prints a random poem from the Wingmakers"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Xe/pemci"
homepage = "https://github.com/Xe/pemci"

[[module]]
name = "pemci"
source = "main.wasm"
abi = "none"

[[command]]
name = "pemci"
module = "pemci"
